// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_module_hart (
        ap_ready,
        inst,
        pc,
        op1,
        op2,
        ap_return_0,
        ap_return_1,
        ap_return_2
);


output   ap_ready;
input  [31:0] inst;
input  [31:0] pc;
input  [31:0] op1;
input  [31:0] op2;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [0:0] ap_return_2;

wire    call_ret_OP_AL_32I_fu_229_ap_ready;
wire   [6:0] call_ret_OP_AL_32I_fu_229_opcode;
wire   [6:0] call_ret_OP_AL_32I_fu_229_func7;
wire   [2:0] call_ret_OP_AL_32I_fu_229_func3;
wire   [31:0] call_ret_OP_AL_32I_fu_229_ap_return_0;
wire   [0:0] call_ret_OP_AL_32I_fu_229_ap_return_1;
reg   [31:0] ap_phi_mux_agg_result_result_0_phi_fu_131_p22;
wire   [6:0] opcode_V_fu_248_p1;
wire   [31:0] p_Result_5_fu_405_p4;
wire   [31:0] res_result_V_3_fu_416_p2;
wire   [31:0] res_result_V_2_fu_429_p2;
wire   [31:0] res_result_V_1_fu_446_p3;
wire   [2:0] func3_V_fu_253_p4;
reg   [31:0] ap_phi_mux_phi_ln46_phi_fu_164_p22;
wire   [31:0] grp_fu_240_p2;
wire  signed [31:0] sext_ln5_4_fu_483_p1;
wire  signed [31:0] sext_ln5_3_fu_502_p1;
wire  signed [31:0] sext_ln5_2_fu_521_p1;
wire  signed [31:0] sext_ln5_1_fu_540_p1;
wire  signed [31:0] sext_ln5_fu_559_p1;
reg   [0:0] ap_phi_mux_phi_ln46_1_phi_fu_195_p22;
wire   [19:0] imm_31_12_fu_275_p4;
wire   [0:0] p_Result_s_fu_289_p3;
wire   [0:0] p_Result_2_fu_297_p3;
wire   [5:0] v2_V_1_fu_305_p4;
wire   [3:0] v2_V_fu_315_p4;
wire   [7:0] v2_V_4_fu_339_p4;
wire   [0:0] p_Result_3_fu_349_p3;
wire   [9:0] v2_V_2_fu_357_p4;
wire   [20:0] r_V_4_fu_367_p6;
wire   [11:0] p_Result_4_fu_385_p4;
wire   [31:0] zext_ln628_fu_395_p1;
wire   [31:0] p_Val2_s_fu_399_p2;
wire  signed [31:0] sext_ln1669_fu_381_p1;
wire  signed [31:0] sext_ln22_fu_285_p1;
wire   [31:0] add_ln32_fu_423_p2;
wire   [19:0] tmp_fu_436_p4;
wire   [0:0] icmp_ln1027_1_fu_455_p2;
wire   [13:0] r_V_fu_461_p6;
wire   [13:0] mdf_V_4_fu_475_p3;
wire   [0:0] icmp_ln1035_fu_488_p2;
wire   [12:0] r_V_3_fu_325_p6;
wire   [12:0] mdf_V_3_fu_494_p3;
wire   [0:0] icmp_ln1027_fu_507_p2;
wire   [12:0] mdf_V_2_fu_513_p3;
wire   [0:0] icmp_ln1023_fu_526_p2;
wire   [12:0] mdf_V_1_fu_532_p3;
wire   [0:0] icmp_ln1019_fu_545_p2;
wire   [12:0] mdf_V_fu_551_p3;
wire    ap_ce_reg;

top_module_OP_AL_32I call_ret_OP_AL_32I_fu_229(
    .ap_ready(call_ret_OP_AL_32I_fu_229_ap_ready),
    .opcode(call_ret_OP_AL_32I_fu_229_opcode),
    .func7(call_ret_OP_AL_32I_fu_229_func7),
    .func3(call_ret_OP_AL_32I_fu_229_func3),
    .op1(op1),
    .op2(op2),
    .ap_return_0(call_ret_OP_AL_32I_fu_229_ap_return_0),
    .ap_return_1(call_ret_OP_AL_32I_fu_229_ap_return_1)
);

always @ (*) begin
    if (((~(func3_V_fu_253_p4 == 3'd6) & ~(func3_V_fu_253_p4 == 3'd5) & ~(func3_V_fu_253_p4 == 3'd4) & ~(func3_V_fu_253_p4 == 3'd1) & ~(func3_V_fu_253_p4 == 3'd0) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd6) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd5) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd4) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd1) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd0) & (opcode_V_fu_248_p1 == 7'd99)))) begin
        ap_phi_mux_agg_result_result_0_phi_fu_131_p22 = 32'd0;
    end else if ((opcode_V_fu_248_p1 == 7'd55)) begin
        ap_phi_mux_agg_result_result_0_phi_fu_131_p22 = res_result_V_1_fu_446_p3;
    end else if ((opcode_V_fu_248_p1 == 7'd23)) begin
        ap_phi_mux_agg_result_result_0_phi_fu_131_p22 = res_result_V_2_fu_429_p2;
    end else if ((opcode_V_fu_248_p1 == 7'd111)) begin
        ap_phi_mux_agg_result_result_0_phi_fu_131_p22 = res_result_V_3_fu_416_p2;
    end else if ((opcode_V_fu_248_p1 == 7'd103)) begin
        ap_phi_mux_agg_result_result_0_phi_fu_131_p22 = p_Result_5_fu_405_p4;
    end else if ((~(opcode_V_fu_248_p1 == 7'd103) & ~(opcode_V_fu_248_p1 == 7'd111) & ~(opcode_V_fu_248_p1 == 7'd23) & ~(opcode_V_fu_248_p1 == 7'd55) & ~(opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_result_0_phi_fu_131_p22 = call_ret_OP_AL_32I_fu_229_ap_return_0;
    end else begin
        ap_phi_mux_agg_result_result_0_phi_fu_131_p22 = 'bx;
    end
end

always @ (*) begin
    if ((((func3_V_fu_253_p4 == 3'd6) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd5) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd4) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd1) & (opcode_V_fu_248_p1 == 7'd99)) | ((func3_V_fu_253_p4 == 3'd0) & (opcode_V_fu_248_p1 == 7'd99)))) begin
        ap_phi_mux_phi_ln46_1_phi_fu_195_p22 = 1'd0;
    end else if (((opcode_V_fu_248_p1 == 7'd23) | (opcode_V_fu_248_p1 == 7'd55) | (~(func3_V_fu_253_p4 == 3'd6) & ~(func3_V_fu_253_p4 == 3'd5) & ~(func3_V_fu_253_p4 == 3'd4) & ~(func3_V_fu_253_p4 == 3'd1) & ~(func3_V_fu_253_p4 == 3'd0) & (opcode_V_fu_248_p1 == 7'd99)))) begin
        ap_phi_mux_phi_ln46_1_phi_fu_195_p22 = 1'd1;
    end else if ((~(opcode_V_fu_248_p1 == 7'd103) & ~(opcode_V_fu_248_p1 == 7'd111) & ~(opcode_V_fu_248_p1 == 7'd23) & ~(opcode_V_fu_248_p1 == 7'd55) & ~(opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_phi_ln46_1_phi_fu_195_p22 = call_ret_OP_AL_32I_fu_229_ap_return_1;
    end else begin
        ap_phi_mux_phi_ln46_1_phi_fu_195_p22 = 'bx;
    end
end

always @ (*) begin
    if (((func3_V_fu_253_p4 == 3'd0) & (opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = sext_ln5_fu_559_p1;
    end else if (((func3_V_fu_253_p4 == 3'd1) & (opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = sext_ln5_1_fu_540_p1;
    end else if (((func3_V_fu_253_p4 == 3'd4) & (opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = sext_ln5_2_fu_521_p1;
    end else if (((func3_V_fu_253_p4 == 3'd5) & (opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = sext_ln5_3_fu_502_p1;
    end else if (((func3_V_fu_253_p4 == 3'd6) & (opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = sext_ln5_4_fu_483_p1;
    end else if ((~(func3_V_fu_253_p4 == 3'd6) & ~(func3_V_fu_253_p4 == 3'd5) & ~(func3_V_fu_253_p4 == 3'd4) & ~(func3_V_fu_253_p4 == 3'd1) & ~(func3_V_fu_253_p4 == 3'd0) & (opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = 32'd0;
    end else if (((opcode_V_fu_248_p1 == 7'd103) | (opcode_V_fu_248_p1 == 7'd111))) begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = grp_fu_240_p2;
    end else if ((~(opcode_V_fu_248_p1 == 7'd103) & ~(opcode_V_fu_248_p1 == 7'd111) & ~(opcode_V_fu_248_p1 == 7'd23) & ~(opcode_V_fu_248_p1 == 7'd55) & ~(opcode_V_fu_248_p1 == 7'd99))) begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = 32'd4;
    end else begin
        ap_phi_mux_phi_ln46_phi_fu_164_p22 = 'bx;
    end
end

assign add_ln32_fu_423_p2 = (pc + 32'd12);

assign ap_ready = 1'b1;

assign call_ret_OP_AL_32I_fu_229_func3 = {{inst[14:12]}};

assign call_ret_OP_AL_32I_fu_229_func7 = {{inst[31:25]}};

assign call_ret_OP_AL_32I_fu_229_opcode = inst[6:0];

assign func3_V_fu_253_p4 = {{inst[14:12]}};

assign grp_fu_240_p2 = (pc + 32'd4);

assign icmp_ln1019_fu_545_p2 = ((op1 == op2) ? 1'b1 : 1'b0);

assign icmp_ln1023_fu_526_p2 = ((op1 != op2) ? 1'b1 : 1'b0);

assign icmp_ln1027_1_fu_455_p2 = ((op1 < op2) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_507_p2 = (($signed(op1) < $signed(op2)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_488_p2 = (($signed(op2) > $signed(op1)) ? 1'b1 : 1'b0);

assign imm_31_12_fu_275_p4 = {{inst[31:12]}};

assign mdf_V_1_fu_532_p3 = ((icmp_ln1023_fu_526_p2[0:0] == 1'b1) ? r_V_3_fu_325_p6 : 13'd4);

assign mdf_V_2_fu_513_p3 = ((icmp_ln1027_fu_507_p2[0:0] == 1'b1) ? r_V_3_fu_325_p6 : 13'd4);

assign mdf_V_3_fu_494_p3 = ((icmp_ln1035_fu_488_p2[0:0] == 1'b1) ? r_V_3_fu_325_p6 : 13'd4);

assign mdf_V_4_fu_475_p3 = ((icmp_ln1027_1_fu_455_p2[0:0] == 1'b1) ? r_V_fu_461_p6 : 14'd4);

assign mdf_V_fu_551_p3 = ((icmp_ln1019_fu_545_p2[0:0] == 1'b1) ? r_V_3_fu_325_p6 : 13'd4);

assign opcode_V_fu_248_p1 = inst[6:0];

assign p_Result_2_fu_297_p3 = inst[32'd7];

assign p_Result_3_fu_349_p3 = inst[32'd20];

assign p_Result_4_fu_385_p4 = {{inst[31:20]}};

assign p_Result_5_fu_405_p4 = {p_Val2_s_fu_399_p2[32-1:1], |(1'd0)};

assign p_Result_s_fu_289_p3 = inst[32'd31];

assign p_Val2_s_fu_399_p2 = (zext_ln628_fu_395_p1 + op1);

assign r_V_3_fu_325_p6 = {{{{{p_Result_s_fu_289_p3}, {p_Result_2_fu_297_p3}}, {v2_V_1_fu_305_p4}}, {v2_V_fu_315_p4}}, {1'd0}};

assign r_V_4_fu_367_p6 = {{{{{p_Result_s_fu_289_p3}, {v2_V_4_fu_339_p4}}, {p_Result_3_fu_349_p3}}, {v2_V_2_fu_357_p4}}, {1'd0}};

assign r_V_fu_461_p6 = {{{{{p_Result_s_fu_289_p3}, {p_Result_2_fu_297_p3}}, {v2_V_1_fu_305_p4}}, {v2_V_fu_315_p4}}, {2'd0}};

assign res_result_V_1_fu_446_p3 = {{tmp_fu_436_p4}, {12'd0}};

assign res_result_V_2_fu_429_p2 = sext_ln22_fu_285_p1 << add_ln32_fu_423_p2;

assign res_result_V_3_fu_416_p2 = ($signed(sext_ln1669_fu_381_p1) + $signed(pc));

assign sext_ln1669_fu_381_p1 = $signed(r_V_4_fu_367_p6);

assign sext_ln22_fu_285_p1 = $signed(imm_31_12_fu_275_p4);

assign sext_ln5_1_fu_540_p1 = $signed(mdf_V_1_fu_532_p3);

assign sext_ln5_2_fu_521_p1 = $signed(mdf_V_2_fu_513_p3);

assign sext_ln5_3_fu_502_p1 = $signed(mdf_V_3_fu_494_p3);

assign sext_ln5_4_fu_483_p1 = $signed(mdf_V_4_fu_475_p3);

assign sext_ln5_fu_559_p1 = $signed(mdf_V_fu_551_p3);

assign tmp_fu_436_p4 = {{inst[31:12]}};

assign v2_V_1_fu_305_p4 = {{inst[30:25]}};

assign v2_V_2_fu_357_p4 = {{inst[30:21]}};

assign v2_V_4_fu_339_p4 = {{inst[19:12]}};

assign v2_V_fu_315_p4 = {{inst[11:8]}};

assign zext_ln628_fu_395_p1 = p_Result_4_fu_385_p4;

assign ap_return_0 = ap_phi_mux_agg_result_result_0_phi_fu_131_p22;

assign ap_return_1 = ap_phi_mux_phi_ln46_phi_fu_164_p22;

assign ap_return_2 = ap_phi_mux_phi_ln46_1_phi_fu_195_p22;

endmodule //top_module_hart
