-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hart_OP_AL_32I is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    opcode_val : IN STD_LOGIC_VECTOR (6 downto 0);
    func7_val : IN STD_LOGIC_VECTOR (6 downto 0);
    func3_val : IN STD_LOGIC_VECTOR (2 downto 0);
    op1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    op2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of hart_OP_AL_32I is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv7_33 : STD_LOGIC_VECTOR (6 downto 0) := "0110011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_20 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_261_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal opcode_val_read_read_fu_78_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal func3_val_read_read_fu_66_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal func7_val_read_read_fu_72_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_267_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_273_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_279_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_293_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_353_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_285_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_305_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_13_fu_371_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln53_fu_383_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln52_fu_393_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shr_i4_fu_401_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ashr_ln65_fu_407_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_534 : STD_LOGIC_VECTOR (0 downto 0);
    signal ashr_ln37_fu_419_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln37_fu_425_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_12_fu_431_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln24_fu_443_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln23_fu_453_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln22_fu_457_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ashr_ln22_fu_463_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp56_0_reg_84 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_rd_val_14_phi_fu_97_p60 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_14_reg_93 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln58_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_1_fu_469_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_phi_mux_status_phi_fu_169_p60 : STD_LOGIC_VECTOR (0 downto 0);
    signal status_reg_164 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_299_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shamt_fu_349_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln58_fu_367_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_2_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rd_val_1_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln65_fu_397_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln37_fu_413_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_9_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rd_val_8_fu_447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_condition_409 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_return_0_preg <= ap_phi_mux_rd_val_14_phi_fu_97_p60;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_return_1_preg <= ap_phi_mux_status_phi_fu_169_p60;
                end if; 
            end if;
        end if;
    end process;


    rd_val_14_reg_93_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_534 = ap_const_lv1_1))) then 
                rd_val_14_reg_93 <= xor_ln37_1_fu_469_p2;
            elsif (((tmp_fu_353_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= shl_ln22_fu_457_p2;
            elsif (((tmp_fu_353_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= ashr_ln22_fu_463_p2;
            elsif (((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_2) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= zext_ln23_fu_453_p1;
            elsif (((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_3) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= zext_ln24_fu_443_p1;
            elsif (((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= rd_val_12_fu_431_p2;
            elsif (((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln58_fu_361_p2 = ap_const_lv1_1))) then 
                rd_val_14_reg_93 <= rd_val_13_fu_371_p2;
            elsif ((((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                rd_val_14_reg_93 <= grp_fu_279_p2;
            elsif (((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_2) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= zext_ln52_fu_393_p1;
            elsif (((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_3) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= zext_ln53_fu_383_p1;
            elsif ((((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_4) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_4) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                rd_val_14_reg_93 <= grp_fu_273_p2;
            elsif ((((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_6) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_6) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                rd_val_14_reg_93 <= grp_fu_267_p2;
            elsif ((((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_7) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_7) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                rd_val_14_reg_93 <= grp_fu_261_p2;
            elsif ((((grp_fu_285_p3 = ap_const_lv1_0) and (tmp_fu_353_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_fu_353_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_fu_353_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                rd_val_14_reg_93 <= grp_fu_293_p2;
            elsif ((((grp_fu_285_p3 = ap_const_lv1_0) and (tmp_fu_353_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_fu_353_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_fu_353_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                rd_val_14_reg_93 <= grp_fu_305_p2;
            elsif (((grp_fu_285_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= shr_i4_fu_401_p2;
            elsif (((grp_fu_285_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rd_val_14_reg_93 <= ashr_ln65_fu_407_p2;
            elsif (((not((func3_val_read_read_fu_66_p2 = ap_const_lv3_5)) and not((func3_val_read_read_fu_66_p2 = ap_const_lv3_0)) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((func7_val_read_read_fu_72_p2 = ap_const_lv7_20)) and not((func7_val_read_read_fu_72_p2 = ap_const_lv7_0)) and (ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((func7_val_read_read_fu_72_p2 = ap_const_lv7_20)) and not((func7_val_read_read_fu_72_p2 = ap_const_lv7_0)) and (ap_start = ap_const_logic_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((opcode_val_read_read_fu_78_p2 = ap_const_lv7_33)) and not((opcode_val_read_read_fu_78_p2 = ap_const_lv7_13)) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) 
    or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln58_fu_361_p2 = ap_const_lv1_0)))) then 
                rd_val_14_reg_93 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    status_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((grp_fu_285_p3 = ap_const_lv1_0) and (tmp_fu_353_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_285_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_285_p3 = ap_const_lv1_0) and (tmp_fu_353_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 
    = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_534 = ap_const_lv1_1)) or ((tmp_fu_353_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_fu_353_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_fu_353_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_285_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) 
    and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_4) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_6) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 
    = ap_const_lv3_0) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_4) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_6) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_7) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_2) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 
    = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_3) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_7) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln58_fu_361_p2 = ap_const_lv1_1)) or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_2) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_3) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) 
    or ((tmp_fu_353_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_fu_353_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_fu_353_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                status_reg_164 <= ap_const_lv1_0;
            elsif (((not((func3_val_read_read_fu_66_p2 = ap_const_lv3_5)) and not((func3_val_read_read_fu_66_p2 = ap_const_lv3_0)) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((func7_val_read_read_fu_72_p2 = ap_const_lv7_20)) and not((func7_val_read_read_fu_72_p2 = ap_const_lv7_0)) and (ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((func7_val_read_read_fu_72_p2 = ap_const_lv7_20)) and not((func7_val_read_read_fu_72_p2 = ap_const_lv7_0)) and (ap_start = ap_const_logic_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((opcode_val_read_read_fu_78_p2 = ap_const_lv7_33)) and not((opcode_val_read_read_fu_78_p2 = ap_const_lv7_13)) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) 
    or ((ap_start = ap_const_logic_1) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_13) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln58_fu_361_p2 = ap_const_lv1_0)))) then 
                status_reg_164 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    tmp56_0_reg_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_409)) then
                if ((tmp_fu_353_p3 = ap_const_lv1_0)) then 
                    tmp56_0_reg_84 <= ashr_ln37_fu_419_p2;
                elsif ((tmp_fu_353_p3 = ap_const_lv1_1)) then 
                    tmp56_0_reg_84 <= shl_ln37_fu_425_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                tmp_1_reg_534 <= op1_val(31 downto 31);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_condition_409_assign_proc : process(ap_start, ap_CS_fsm_state1, opcode_val_read_read_fu_78_p2, func3_val_read_read_fu_66_p2, func7_val_read_read_fu_72_p2, grp_fu_285_p3)
    begin
                ap_condition_409 <= ((grp_fu_285_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_rd_val_14_phi_fu_97_p60_assign_proc : process(opcode_val_read_read_fu_78_p2, func3_val_read_read_fu_66_p2, func7_val_read_read_fu_72_p2, tmp_1_reg_534, rd_val_14_reg_93, xor_ln37_1_fu_469_p2, ap_CS_fsm_state2)
    begin
        if (((func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_534 = ap_const_lv1_1))) then 
            ap_phi_mux_rd_val_14_phi_fu_97_p60 <= xor_ln37_1_fu_469_p2;
        else 
            ap_phi_mux_rd_val_14_phi_fu_97_p60 <= rd_val_14_reg_93;
        end if; 
    end process;


    ap_phi_mux_status_phi_fu_169_p60_assign_proc : process(opcode_val_read_read_fu_78_p2, func3_val_read_read_fu_66_p2, func7_val_read_read_fu_72_p2, tmp_1_reg_534, ap_CS_fsm_state2, status_reg_164)
    begin
        if (((func7_val_read_read_fu_72_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_66_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_78_p2 = ap_const_lv7_33) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_534 = ap_const_lv1_1))) then 
            ap_phi_mux_status_phi_fu_169_p60 <= ap_const_lv1_0;
        else 
            ap_phi_mux_status_phi_fu_169_p60 <= status_reg_164;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_phi_mux_rd_val_14_phi_fu_97_p60, ap_CS_fsm_state2, ap_return_0_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_return_0 <= ap_phi_mux_rd_val_14_phi_fu_97_p60;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state2, ap_phi_mux_status_phi_fu_169_p60, ap_return_1_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_return_1 <= ap_phi_mux_status_phi_fu_169_p60;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;

    ashr_ln22_fu_463_p2 <= std_logic_vector(shift_right(signed(op1_val),to_integer(unsigned('0' & grp_fu_299_p2(31-1 downto 0)))));
    ashr_ln37_fu_419_p2 <= std_logic_vector(shift_right(signed(xor_ln37_fu_413_p2),to_integer(unsigned('0' & op2_val(31-1 downto 0)))));
    ashr_ln65_fu_407_p2 <= std_logic_vector(shift_right(signed(op1_val),to_integer(unsigned('0' & zext_ln65_fu_397_p1(31-1 downto 0)))));
    func3_val_read_read_fu_66_p2 <= func3_val;
    func7_val_read_read_fu_72_p2 <= func7_val;
    grp_fu_261_p2 <= (op2_val and op1_val);
    grp_fu_267_p2 <= (op2_val or op1_val);
    grp_fu_273_p2 <= (op2_val xor op1_val);
    grp_fu_279_p2 <= std_logic_vector(unsigned(op2_val) + unsigned(op1_val));
    grp_fu_285_p3 <= op1_val(31 downto 31);
    grp_fu_293_p2 <= std_logic_vector(shift_right(unsigned(op1_val),to_integer(unsigned('0' & op2_val(31-1 downto 0)))));
    grp_fu_299_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(op2_val));
    grp_fu_305_p2 <= std_logic_vector(shift_left(unsigned(op1_val),to_integer(unsigned('0' & grp_fu_299_p2(31-1 downto 0)))));
    icmp_ln58_fu_361_p2 <= "1" when (func7_val = ap_const_lv7_0) else "0";
    opcode_val_read_read_fu_78_p2 <= opcode_val;
    rd_val_12_fu_431_p2 <= std_logic_vector(unsigned(op1_val) - unsigned(op2_val));
    rd_val_13_fu_371_p2 <= std_logic_vector(shift_left(unsigned(op1_val),to_integer(unsigned('0' & zext_ln58_fu_367_p1(31-1 downto 0)))));
    rd_val_1_fu_387_p2 <= "1" when (signed(op2_val) > signed(op1_val)) else "0";
    rd_val_2_fu_377_p2 <= "1" when (unsigned(op2_val) > unsigned(op1_val)) else "0";
    rd_val_8_fu_447_p2 <= "1" when (signed(op1_val) < signed(op2_val)) else "0";
    rd_val_9_fu_437_p2 <= "1" when (unsigned(op1_val) < unsigned(op2_val)) else "0";
    shamt_fu_349_p1 <= op2_val(6 - 1 downto 0);
    shl_ln22_fu_457_p2 <= std_logic_vector(shift_left(unsigned(op1_val),to_integer(unsigned('0' & op2_val(31-1 downto 0)))));
    shl_ln37_fu_425_p2 <= std_logic_vector(shift_left(unsigned(xor_ln37_fu_413_p2),to_integer(unsigned('0' & grp_fu_299_p2(31-1 downto 0)))));
    shr_i4_fu_401_p2 <= std_logic_vector(shift_right(unsigned(op1_val),to_integer(unsigned('0' & zext_ln65_fu_397_p1(31-1 downto 0)))));
    tmp_fu_353_p3 <= op2_val(31 downto 31);
    xor_ln37_1_fu_469_p2 <= (tmp56_0_reg_84 xor ap_const_lv32_FFFFFFFF);
    xor_ln37_fu_413_p2 <= (op1_val xor ap_const_lv32_FFFFFFFF);
    zext_ln23_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_8_fu_447_p2),32));
    zext_ln24_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_9_fu_437_p2),32));
    zext_ln52_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_1_fu_387_p2),32));
    zext_ln53_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_2_fu_377_p2),32));
    zext_ln58_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shamt_fu_349_p1),32));
    zext_ln65_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shamt_fu_349_p1),32));
end behav;
