-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_module_OP_AL_32I is
port (
    ap_ready : OUT STD_LOGIC;
    inst_val : IN STD_LOGIC_VECTOR (31 downto 0);
    func7_val : IN STD_LOGIC_VECTOR (6 downto 0);
    func3_val : IN STD_LOGIC_VECTOR (2 downto 0);
    op1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    op2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of top_module_OP_AL_32I is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv7_33 : STD_LOGIC_VECTOR (6 downto 0) := "0110011";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv7_20 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal shl_ln38_fu_464_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp57_0_phi_fu_101_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal opcode_fu_309_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal func3_val_read_read_fu_80_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal func7_val_read_read_fu_86_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_267_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_275_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ashr_ln38_fu_457_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_rd_val_15_phi_fu_110_p58 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_13_fu_444_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ashr_ln70_fu_437_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shr_i4_fu_430_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln7_fu_360_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_4_fu_381_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_3_fu_390_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln54_fu_403_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln53_fu_414_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_fu_419_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_14_fu_347_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln59_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rd_val_6_fu_542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_12_fu_478_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_297_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_283_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_11_fu_485_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_10_fu_492_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln25_fu_505_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln24_fu_516_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_7_fu_535_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ashr_ln23_fu_528_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln23_fu_521_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln38_1_fu_471_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_valid_phi_fu_178_p58 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_291_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal immediate_fu_313_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shamt_fu_327_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln59_fu_343_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln10_fu_305_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal rd_val_5_fu_354_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_7_fu_371_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal or_ln56_fu_365_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln13_fu_323_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_2_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rd_val_1_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln70_fu_426_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln38_fu_451_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_9_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rd_val_8_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_30 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_condition_30_assign_proc : process(opcode_fu_309_p1, func3_val_read_read_fu_80_p2, func7_val_read_read_fu_86_p2, grp_fu_267_p3)
    begin
                ap_condition_30 <= ((grp_fu_267_p3 = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33));
    end process;


    ap_phi_mux_rd_val_15_phi_fu_110_p58_assign_proc : process(opcode_fu_309_p1, func3_val_read_read_fu_80_p2, func7_val_read_read_fu_86_p2, grp_fu_267_p3, grp_fu_275_p3, rd_val_13_fu_444_p2, ashr_ln70_fu_437_p2, shr_i4_fu_430_p2, zext_ln7_fu_360_p1, rd_val_4_fu_381_p3, rd_val_3_fu_390_p2, zext_ln54_fu_403_p1, zext_ln53_fu_414_p1, rd_val_fu_419_p2, rd_val_14_fu_347_p2, icmp_ln59_fu_337_p2, rd_val_6_fu_542_p2, rd_val_12_fu_478_p2, grp_fu_297_p2, grp_fu_283_p2, rd_val_11_fu_485_p2, rd_val_10_fu_492_p2, zext_ln25_fu_505_p1, zext_ln24_fu_516_p1, rd_val_7_fu_535_p2, ashr_ln23_fu_528_p2, shl_ln23_fu_521_p2, xor_ln38_1_fu_471_p2)
    begin
        if (((grp_fu_267_p3 = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= xor_ln38_1_fu_471_p2;
        elsif (((grp_fu_275_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_1) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= shl_ln23_fu_521_p2;
        elsif (((grp_fu_275_p3 = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_1) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= ashr_ln23_fu_528_p2;
        elsif (((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_0) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_7_fu_535_p2;
        elsif (((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_2) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= zext_ln24_fu_516_p1;
        elsif (((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_3) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= zext_ln25_fu_505_p1;
        elsif (((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_4) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_10_fu_492_p2;
        elsif (((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_6) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_11_fu_485_p2;
        elsif ((((grp_fu_275_p3 = ap_const_lv1_0) and (grp_fu_267_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((grp_fu_275_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= grp_fu_283_p2;
        elsif ((((grp_fu_275_p3 = ap_const_lv1_1) and (grp_fu_267_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((grp_fu_275_p3 = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= grp_fu_297_p2;
        elsif (((func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_0) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_12_fu_478_p2;
        elsif (((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_7) and (opcode_fu_309_p1 = ap_const_lv7_33))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_6_fu_542_p2;
        elsif (((icmp_ln59_fu_337_p2 = ap_const_lv1_1) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_1) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_14_fu_347_p2;
        elsif (((func3_val_read_read_fu_80_p2 = ap_const_lv3_0) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_fu_419_p2;
        elsif (((func3_val_read_read_fu_80_p2 = ap_const_lv3_2) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= zext_ln53_fu_414_p1;
        elsif (((func3_val_read_read_fu_80_p2 = ap_const_lv3_3) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= zext_ln54_fu_403_p1;
        elsif (((func3_val_read_read_fu_80_p2 = ap_const_lv3_4) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_3_fu_390_p2;
        elsif (((func3_val_read_read_fu_80_p2 = ap_const_lv3_6) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_4_fu_381_p3;
        elsif (((func3_val_read_read_fu_80_p2 = ap_const_lv3_7) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= zext_ln7_fu_360_p1;
        elsif (((grp_fu_267_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= shr_i4_fu_430_p2;
        elsif (((grp_fu_267_p3 = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= ashr_ln70_fu_437_p2;
        elsif (((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_13))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= rd_val_13_fu_444_p2;
        elsif (((not((func3_val_read_read_fu_80_p2 = ap_const_lv3_0)) and not((func3_val_read_read_fu_80_p2 = ap_const_lv3_5)) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (opcode_fu_309_p1 = ap_const_lv7_33)) or (not((func7_val_read_read_fu_86_p2 = ap_const_lv7_0)) and not((func7_val_read_read_fu_86_p2 = ap_const_lv7_20)) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_13)) or (not((func7_val_read_read_fu_86_p2 = ap_const_lv7_0)) and not((func7_val_read_read_fu_86_p2 = ap_const_lv7_20)) and (opcode_fu_309_p1 = ap_const_lv7_33)) or (not((opcode_fu_309_p1 = ap_const_lv7_13)) and not((opcode_fu_309_p1 = ap_const_lv7_33))) or ((icmp_ln59_fu_337_p2 = ap_const_lv1_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_1) and (opcode_fu_309_p1 = ap_const_lv7_13)))) then 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= ap_const_lv32_0;
        else 
            ap_phi_mux_rd_val_15_phi_fu_110_p58 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_tmp57_0_phi_fu_101_p4_assign_proc : process(shl_ln38_fu_464_p2, grp_fu_275_p3, ashr_ln38_fu_457_p2, ap_condition_30)
    begin
        if ((ap_const_boolean_1 = ap_condition_30)) then
            if ((grp_fu_275_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_tmp57_0_phi_fu_101_p4 <= ashr_ln38_fu_457_p2;
            elsif ((grp_fu_275_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_tmp57_0_phi_fu_101_p4 <= shl_ln38_fu_464_p2;
            else 
                ap_phi_mux_tmp57_0_phi_fu_101_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_tmp57_0_phi_fu_101_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_valid_phi_fu_178_p58_assign_proc : process(opcode_fu_309_p1, func3_val_read_read_fu_80_p2, func7_val_read_read_fu_86_p2, grp_fu_267_p3, grp_fu_275_p3, icmp_ln59_fu_337_p2)
    begin
        if ((((icmp_ln59_fu_337_p2 = ap_const_lv1_1) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_1) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((func3_val_read_read_fu_80_p2 = ap_const_lv3_0) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((func3_val_read_read_fu_80_p2 = ap_const_lv3_2) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((func3_val_read_read_fu_80_p2 = ap_const_lv3_3) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((func3_val_read_read_fu_80_p2 = ap_const_lv3_4) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((func3_val_read_read_fu_80_p2 = ap_const_lv3_6) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((func3_val_read_read_fu_80_p2 = ap_const_lv3_7) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((grp_fu_267_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_0) and (opcode_fu_309_p1 = ap_const_lv7_33)) 
    or ((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_2) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_3) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_4) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_6) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_7) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((grp_fu_275_p3 = ap_const_lv1_0) and (grp_fu_267_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 
    = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((grp_fu_275_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_1) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((grp_fu_275_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((grp_fu_275_p3 = ap_const_lv1_1) and (grp_fu_267_p3 = ap_const_lv1_0) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((grp_fu_275_p3 = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_1) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((grp_fu_275_p3 = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((grp_fu_267_p3 
    = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_13)) or ((grp_fu_267_p3 = ap_const_lv1_1) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_33)) or ((func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_0) and (opcode_fu_309_p1 = ap_const_lv7_33)))) then 
            ap_phi_mux_valid_phi_fu_178_p58 <= ap_const_lv1_1;
        elsif (((not((func3_val_read_read_fu_80_p2 = ap_const_lv3_0)) and not((func3_val_read_read_fu_80_p2 = ap_const_lv3_5)) and (func7_val_read_read_fu_86_p2 = ap_const_lv7_20) and (opcode_fu_309_p1 = ap_const_lv7_33)) or (not((func7_val_read_read_fu_86_p2 = ap_const_lv7_0)) and not((func7_val_read_read_fu_86_p2 = ap_const_lv7_20)) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_5) and (opcode_fu_309_p1 = ap_const_lv7_13)) or (not((func7_val_read_read_fu_86_p2 = ap_const_lv7_0)) and not((func7_val_read_read_fu_86_p2 = ap_const_lv7_20)) and (opcode_fu_309_p1 = ap_const_lv7_33)) or (not((opcode_fu_309_p1 = ap_const_lv7_13)) and not((opcode_fu_309_p1 = ap_const_lv7_33))) or ((icmp_ln59_fu_337_p2 = ap_const_lv1_0) and (func3_val_read_read_fu_80_p2 = ap_const_lv3_1) and (opcode_fu_309_p1 = ap_const_lv7_13)))) then 
            ap_phi_mux_valid_phi_fu_178_p58 <= ap_const_lv1_0;
        else 
            ap_phi_mux_valid_phi_fu_178_p58 <= "X";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return_0 <= ap_phi_mux_rd_val_15_phi_fu_110_p58;
    ap_return_1 <= ap_phi_mux_valid_phi_fu_178_p58;
    ashr_ln23_fu_528_p2 <= std_logic_vector(shift_right(signed(op1_val),to_integer(unsigned('0' & grp_fu_291_p2(31-1 downto 0)))));
    ashr_ln38_fu_457_p2 <= std_logic_vector(shift_right(signed(xor_ln38_fu_451_p2),to_integer(unsigned('0' & op2_val(31-1 downto 0)))));
    ashr_ln70_fu_437_p2 <= std_logic_vector(shift_right(signed(op1_val),to_integer(unsigned('0' & zext_ln70_fu_426_p1(31-1 downto 0)))));
    func3_val_read_read_fu_80_p2 <= func3_val;
    func7_val_read_read_fu_86_p2 <= func7_val;
    grp_fu_267_p3 <= op1_val(31 downto 31);
    grp_fu_275_p3 <= op2_val(31 downto 31);
    grp_fu_283_p2 <= std_logic_vector(shift_right(unsigned(op1_val),to_integer(unsigned('0' & op2_val(31-1 downto 0)))));
    grp_fu_291_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(op2_val));
    grp_fu_297_p2 <= std_logic_vector(shift_left(unsigned(op1_val),to_integer(unsigned('0' & grp_fu_291_p2(31-1 downto 0)))));
    icmp_ln59_fu_337_p2 <= "1" when (func7_val = ap_const_lv7_0) else "0";
    immediate_fu_313_p4 <= inst_val(31 downto 20);
    opcode_fu_309_p1 <= inst_val(7 - 1 downto 0);
    or_ln56_fu_365_p2 <= (trunc_ln10_fu_305_p1 or immediate_fu_313_p4);
    rd_val_10_fu_492_p2 <= (op2_val xor op1_val);
    rd_val_11_fu_485_p2 <= (op2_val or op1_val);
    rd_val_12_fu_478_p2 <= std_logic_vector(unsigned(op1_val) - unsigned(op2_val));
    rd_val_13_fu_444_p2 <= std_logic_vector(shift_right(unsigned(op1_val),to_integer(unsigned('0' & zext_ln13_fu_323_p1(31-1 downto 0)))));
    rd_val_14_fu_347_p2 <= std_logic_vector(shift_left(unsigned(op1_val),to_integer(unsigned('0' & zext_ln59_fu_343_p1(31-1 downto 0)))));
    rd_val_1_fu_408_p2 <= "1" when (signed(zext_ln13_fu_323_p1) > signed(op1_val)) else "0";
    rd_val_2_fu_397_p2 <= "1" when (unsigned(zext_ln13_fu_323_p1) > unsigned(op1_val)) else "0";
    rd_val_3_fu_390_p2 <= (zext_ln13_fu_323_p1 xor op1_val);
    rd_val_4_fu_381_p3 <= (tmp_7_fu_371_p4 & or_ln56_fu_365_p2);
    rd_val_5_fu_354_p2 <= (trunc_ln10_fu_305_p1 and immediate_fu_313_p4);
    rd_val_6_fu_542_p2 <= (op2_val and op1_val);
    rd_val_7_fu_535_p2 <= std_logic_vector(unsigned(op2_val) + unsigned(op1_val));
    rd_val_8_fu_510_p2 <= "1" when (signed(op1_val) < signed(op2_val)) else "0";
    rd_val_9_fu_499_p2 <= "1" when (unsigned(op1_val) < unsigned(op2_val)) else "0";
    rd_val_fu_419_p2 <= std_logic_vector(unsigned(zext_ln13_fu_323_p1) + unsigned(op1_val));
    shamt_fu_327_p4 <= inst_val(25 downto 20);
    shl_ln23_fu_521_p2 <= std_logic_vector(shift_left(unsigned(op1_val),to_integer(unsigned('0' & op2_val(31-1 downto 0)))));
    shl_ln38_fu_464_p2 <= std_logic_vector(shift_left(unsigned(xor_ln38_fu_451_p2),to_integer(unsigned('0' & grp_fu_291_p2(31-1 downto 0)))));
    shr_i4_fu_430_p2 <= std_logic_vector(shift_right(unsigned(op1_val),to_integer(unsigned('0' & zext_ln70_fu_426_p1(31-1 downto 0)))));
    tmp_7_fu_371_p4 <= op1_val(31 downto 12);
    trunc_ln10_fu_305_p1 <= op1_val(12 - 1 downto 0);
    xor_ln38_1_fu_471_p2 <= (ap_phi_mux_tmp57_0_phi_fu_101_p4 xor ap_const_lv32_FFFFFFFF);
    xor_ln38_fu_451_p2 <= (op1_val xor ap_const_lv32_FFFFFFFF);
    zext_ln13_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(immediate_fu_313_p4),32));
    zext_ln24_fu_516_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_8_fu_510_p2),32));
    zext_ln25_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_9_fu_499_p2),32));
    zext_ln53_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_1_fu_408_p2),32));
    zext_ln54_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_2_fu_397_p2),32));
    zext_ln59_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shamt_fu_327_p4),32));
    zext_ln70_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shamt_fu_327_p4),32));
    zext_ln7_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_val_5_fu_354_p2),32));
end behav;
