-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_module_hart is
port (
    ap_ready : OUT STD_LOGIC;
    inst : IN STD_LOGIC_VECTOR (31 downto 0);
    pc : IN STD_LOGIC_VECTOR (31 downto 0);
    op1 : IN STD_LOGIC_VECTOR (31 downto 0);
    op2 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of top_module_hart is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv7_17 : STD_LOGIC_VECTOR (6 downto 0) := "0010111";
    constant ap_const_lv7_6F : STD_LOGIC_VECTOR (6 downto 0) := "1101111";
    constant ap_const_lv7_67 : STD_LOGIC_VECTOR (6 downto 0) := "1100111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv14_4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_const_lv13_4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal call_ret_OP_AL_32I_fu_229_ap_ready : STD_LOGIC;
    signal call_ret_OP_AL_32I_fu_229_opcode : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret_OP_AL_32I_fu_229_func7 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret_OP_AL_32I_fu_229_func3 : STD_LOGIC_VECTOR (2 downto 0);
    signal call_ret_OP_AL_32I_fu_229_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_OP_AL_32I_fu_229_ap_return_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_agg_result_result_0_phi_fu_131_p22 : STD_LOGIC_VECTOR (31 downto 0);
    signal opcode_V_fu_248_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_5_fu_405_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_result_V_3_fu_416_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_result_V_2_fu_429_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_result_V_1_fu_446_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal func3_V_fu_253_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_phi_ln46_phi_fu_164_p22 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln5_4_fu_483_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln5_3_fu_502_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln5_2_fu_521_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln5_1_fu_540_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln5_fu_559_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_phi_ln46_1_phi_fu_195_p22 : STD_LOGIC_VECTOR (0 downto 0);
    signal imm_31_12_fu_275_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Result_s_fu_289_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_297_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal v2_V_1_fu_305_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal v2_V_fu_315_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal v2_V_4_fu_339_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_3_fu_349_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal v2_V_2_fu_357_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_4_fu_367_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Result_4_fu_385_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln628_fu_395_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_s_fu_399_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1669_fu_381_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln22_fu_285_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln32_fu_423_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_436_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal icmp_ln1027_1_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_461_p6 : STD_LOGIC_VECTOR (13 downto 0);
    signal mdf_V_4_fu_475_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln1035_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_3_fu_325_p6 : STD_LOGIC_VECTOR (12 downto 0);
    signal mdf_V_3_fu_494_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln1027_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mdf_V_2_fu_513_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln1023_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mdf_V_1_fu_532_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln1019_fu_545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mdf_V_fu_551_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_module_OP_AL_32I IS
    port (
        ap_ready : OUT STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (6 downto 0);
        func7 : IN STD_LOGIC_VECTOR (6 downto 0);
        func3 : IN STD_LOGIC_VECTOR (2 downto 0);
        op1 : IN STD_LOGIC_VECTOR (31 downto 0);
        op2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    call_ret_OP_AL_32I_fu_229 : component top_module_OP_AL_32I
    port map (
        ap_ready => call_ret_OP_AL_32I_fu_229_ap_ready,
        opcode => call_ret_OP_AL_32I_fu_229_opcode,
        func7 => call_ret_OP_AL_32I_fu_229_func7,
        func3 => call_ret_OP_AL_32I_fu_229_func3,
        op1 => op1,
        op2 => op2,
        ap_return_0 => call_ret_OP_AL_32I_fu_229_ap_return_0,
        ap_return_1 => call_ret_OP_AL_32I_fu_229_ap_return_1);




    add_ln32_fu_423_p2 <= std_logic_vector(unsigned(pc) + unsigned(ap_const_lv32_C));

    ap_phi_mux_agg_result_result_0_phi_fu_131_p22_assign_proc : process(call_ret_OP_AL_32I_fu_229_ap_return_0, opcode_V_fu_248_p1, p_Result_5_fu_405_p4, res_result_V_3_fu_416_p2, res_result_V_2_fu_429_p2, res_result_V_1_fu_446_p3, func3_V_fu_253_p4)
    begin
        if (((not((func3_V_fu_253_p4 = ap_const_lv3_6)) and not((func3_V_fu_253_p4 = ap_const_lv3_5)) and not((func3_V_fu_253_p4 = ap_const_lv3_4)) and not((func3_V_fu_253_p4 = ap_const_lv3_1)) and not((func3_V_fu_253_p4 = ap_const_lv3_0)) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_6) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_5) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_4) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_1) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_0) and (opcode_V_fu_248_p1 = ap_const_lv7_63)))) then 
            ap_phi_mux_agg_result_result_0_phi_fu_131_p22 <= ap_const_lv32_0;
        elsif ((opcode_V_fu_248_p1 = ap_const_lv7_37)) then 
            ap_phi_mux_agg_result_result_0_phi_fu_131_p22 <= res_result_V_1_fu_446_p3;
        elsif ((opcode_V_fu_248_p1 = ap_const_lv7_17)) then 
            ap_phi_mux_agg_result_result_0_phi_fu_131_p22 <= res_result_V_2_fu_429_p2;
        elsif ((opcode_V_fu_248_p1 = ap_const_lv7_6F)) then 
            ap_phi_mux_agg_result_result_0_phi_fu_131_p22 <= res_result_V_3_fu_416_p2;
        elsif ((opcode_V_fu_248_p1 = ap_const_lv7_67)) then 
            ap_phi_mux_agg_result_result_0_phi_fu_131_p22 <= p_Result_5_fu_405_p4;
        elsif ((not((opcode_V_fu_248_p1 = ap_const_lv7_67)) and not((opcode_V_fu_248_p1 = ap_const_lv7_6F)) and not((opcode_V_fu_248_p1 = ap_const_lv7_17)) and not((opcode_V_fu_248_p1 = ap_const_lv7_37)) and not((opcode_V_fu_248_p1 = ap_const_lv7_63)))) then 
            ap_phi_mux_agg_result_result_0_phi_fu_131_p22 <= call_ret_OP_AL_32I_fu_229_ap_return_0;
        else 
            ap_phi_mux_agg_result_result_0_phi_fu_131_p22 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_phi_ln46_1_phi_fu_195_p22_assign_proc : process(call_ret_OP_AL_32I_fu_229_ap_return_1, opcode_V_fu_248_p1, func3_V_fu_253_p4)
    begin
        if ((((func3_V_fu_253_p4 = ap_const_lv3_6) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_5) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_4) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_1) and (opcode_V_fu_248_p1 = ap_const_lv7_63)) or ((func3_V_fu_253_p4 = ap_const_lv3_0) and (opcode_V_fu_248_p1 = ap_const_lv7_63)))) then 
            ap_phi_mux_phi_ln46_1_phi_fu_195_p22 <= ap_const_lv1_0;
        elsif (((opcode_V_fu_248_p1 = ap_const_lv7_17) or (opcode_V_fu_248_p1 = ap_const_lv7_37) or (not((func3_V_fu_253_p4 = ap_const_lv3_6)) and not((func3_V_fu_253_p4 = ap_const_lv3_5)) and not((func3_V_fu_253_p4 = ap_const_lv3_4)) and not((func3_V_fu_253_p4 = ap_const_lv3_1)) and not((func3_V_fu_253_p4 = ap_const_lv3_0)) and (opcode_V_fu_248_p1 = ap_const_lv7_63)))) then 
            ap_phi_mux_phi_ln46_1_phi_fu_195_p22 <= ap_const_lv1_1;
        elsif ((not((opcode_V_fu_248_p1 = ap_const_lv7_67)) and not((opcode_V_fu_248_p1 = ap_const_lv7_6F)) and not((opcode_V_fu_248_p1 = ap_const_lv7_17)) and not((opcode_V_fu_248_p1 = ap_const_lv7_37)) and not((opcode_V_fu_248_p1 = ap_const_lv7_63)))) then 
            ap_phi_mux_phi_ln46_1_phi_fu_195_p22 <= call_ret_OP_AL_32I_fu_229_ap_return_1;
        else 
            ap_phi_mux_phi_ln46_1_phi_fu_195_p22 <= "X";
        end if; 
    end process;


    ap_phi_mux_phi_ln46_phi_fu_164_p22_assign_proc : process(opcode_V_fu_248_p1, func3_V_fu_253_p4, grp_fu_240_p2, sext_ln5_4_fu_483_p1, sext_ln5_3_fu_502_p1, sext_ln5_2_fu_521_p1, sext_ln5_1_fu_540_p1, sext_ln5_fu_559_p1)
    begin
        if (((func3_V_fu_253_p4 = ap_const_lv3_0) and (opcode_V_fu_248_p1 = ap_const_lv7_63))) then 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= sext_ln5_fu_559_p1;
        elsif (((func3_V_fu_253_p4 = ap_const_lv3_1) and (opcode_V_fu_248_p1 = ap_const_lv7_63))) then 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= sext_ln5_1_fu_540_p1;
        elsif (((func3_V_fu_253_p4 = ap_const_lv3_4) and (opcode_V_fu_248_p1 = ap_const_lv7_63))) then 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= sext_ln5_2_fu_521_p1;
        elsif (((func3_V_fu_253_p4 = ap_const_lv3_5) and (opcode_V_fu_248_p1 = ap_const_lv7_63))) then 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= sext_ln5_3_fu_502_p1;
        elsif (((func3_V_fu_253_p4 = ap_const_lv3_6) and (opcode_V_fu_248_p1 = ap_const_lv7_63))) then 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= sext_ln5_4_fu_483_p1;
        elsif ((not((func3_V_fu_253_p4 = ap_const_lv3_6)) and not((func3_V_fu_253_p4 = ap_const_lv3_5)) and not((func3_V_fu_253_p4 = ap_const_lv3_4)) and not((func3_V_fu_253_p4 = ap_const_lv3_1)) and not((func3_V_fu_253_p4 = ap_const_lv3_0)) and (opcode_V_fu_248_p1 = ap_const_lv7_63))) then 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= ap_const_lv32_0;
        elsif (((opcode_V_fu_248_p1 = ap_const_lv7_67) or (opcode_V_fu_248_p1 = ap_const_lv7_6F))) then 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= grp_fu_240_p2;
        elsif ((not((opcode_V_fu_248_p1 = ap_const_lv7_67)) and not((opcode_V_fu_248_p1 = ap_const_lv7_6F)) and not((opcode_V_fu_248_p1 = ap_const_lv7_17)) and not((opcode_V_fu_248_p1 = ap_const_lv7_37)) and not((opcode_V_fu_248_p1 = ap_const_lv7_63)))) then 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= ap_const_lv32_4;
        else 
            ap_phi_mux_phi_ln46_phi_fu_164_p22 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return_0 <= ap_phi_mux_agg_result_result_0_phi_fu_131_p22;
    ap_return_1 <= ap_phi_mux_phi_ln46_phi_fu_164_p22;
    ap_return_2 <= ap_phi_mux_phi_ln46_1_phi_fu_195_p22;
    call_ret_OP_AL_32I_fu_229_func3 <= inst(14 downto 12);
    call_ret_OP_AL_32I_fu_229_func7 <= inst(31 downto 25);
    call_ret_OP_AL_32I_fu_229_opcode <= inst(7 - 1 downto 0);
    func3_V_fu_253_p4 <= inst(14 downto 12);
    grp_fu_240_p2 <= std_logic_vector(unsigned(pc) + unsigned(ap_const_lv32_4));
    icmp_ln1019_fu_545_p2 <= "1" when (op1 = op2) else "0";
    icmp_ln1023_fu_526_p2 <= "0" when (op1 = op2) else "1";
    icmp_ln1027_1_fu_455_p2 <= "1" when (unsigned(op1) < unsigned(op2)) else "0";
    icmp_ln1027_fu_507_p2 <= "1" when (signed(op1) < signed(op2)) else "0";
    icmp_ln1035_fu_488_p2 <= "1" when (signed(op2) > signed(op1)) else "0";
    imm_31_12_fu_275_p4 <= inst(31 downto 12);
    mdf_V_1_fu_532_p3 <= 
        r_V_3_fu_325_p6 when (icmp_ln1023_fu_526_p2(0) = '1') else 
        ap_const_lv13_4;
    mdf_V_2_fu_513_p3 <= 
        r_V_3_fu_325_p6 when (icmp_ln1027_fu_507_p2(0) = '1') else 
        ap_const_lv13_4;
    mdf_V_3_fu_494_p3 <= 
        r_V_3_fu_325_p6 when (icmp_ln1035_fu_488_p2(0) = '1') else 
        ap_const_lv13_4;
    mdf_V_4_fu_475_p3 <= 
        r_V_fu_461_p6 when (icmp_ln1027_1_fu_455_p2(0) = '1') else 
        ap_const_lv14_4;
    mdf_V_fu_551_p3 <= 
        r_V_3_fu_325_p6 when (icmp_ln1019_fu_545_p2(0) = '1') else 
        ap_const_lv13_4;
    opcode_V_fu_248_p1 <= inst(7 - 1 downto 0);
    p_Result_2_fu_297_p3 <= inst(7 downto 7);
    p_Result_3_fu_349_p3 <= inst(20 downto 20);
    p_Result_4_fu_385_p4 <= inst(31 downto 20);
    
    p_Result_5_fu_405_p4_proc : process(p_Val2_s_fu_399_p2)
    begin
        p_Result_5_fu_405_p4 <= p_Val2_s_fu_399_p2;
        p_Result_5_fu_405_p4(0) <= ap_const_lv1_0(0);
    end process;

    p_Result_s_fu_289_p3 <= inst(31 downto 31);
    p_Val2_s_fu_399_p2 <= std_logic_vector(unsigned(zext_ln628_fu_395_p1) + unsigned(op1));
    r_V_3_fu_325_p6 <= ((((p_Result_s_fu_289_p3 & p_Result_2_fu_297_p3) & v2_V_1_fu_305_p4) & v2_V_fu_315_p4) & ap_const_lv1_0);
    r_V_4_fu_367_p6 <= ((((p_Result_s_fu_289_p3 & v2_V_4_fu_339_p4) & p_Result_3_fu_349_p3) & v2_V_2_fu_357_p4) & ap_const_lv1_0);
    r_V_fu_461_p6 <= ((((p_Result_s_fu_289_p3 & p_Result_2_fu_297_p3) & v2_V_1_fu_305_p4) & v2_V_fu_315_p4) & ap_const_lv2_0);
    res_result_V_1_fu_446_p3 <= (tmp_fu_436_p4 & ap_const_lv12_0);
    res_result_V_2_fu_429_p2 <= std_logic_vector(shift_left(unsigned(sext_ln22_fu_285_p1),to_integer(unsigned('0' & add_ln32_fu_423_p2(31-1 downto 0)))));
    res_result_V_3_fu_416_p2 <= std_logic_vector(signed(sext_ln1669_fu_381_p1) + signed(pc));
        sext_ln1669_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_4_fu_367_p6),32));

        sext_ln22_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(imm_31_12_fu_275_p4),32));

        sext_ln5_1_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mdf_V_1_fu_532_p3),32));

        sext_ln5_2_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mdf_V_2_fu_513_p3),32));

        sext_ln5_3_fu_502_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mdf_V_3_fu_494_p3),32));

        sext_ln5_4_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mdf_V_4_fu_475_p3),32));

        sext_ln5_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mdf_V_fu_551_p3),32));

    tmp_fu_436_p4 <= inst(31 downto 12);
    v2_V_1_fu_305_p4 <= inst(30 downto 25);
    v2_V_2_fu_357_p4 <= inst(30 downto 21);
    v2_V_4_fu_339_p4 <= inst(19 downto 12);
    v2_V_fu_315_p4 <= inst(11 downto 8);
    zext_ln628_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_4_fu_385_p4),32));
end behav;
