// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_hart (
        ap_ready,
        inst_val,
        pc_val,
        op1_val,
        op2_val,
        ap_return_0,
        ap_return_1,
        ap_return_2
);


output   ap_ready;
input  [31:0] inst_val;
input  [31:0] pc_val;
input  [31:0] op1_val;
input  [31:0] op2_val;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [0:0] ap_return_2;

wire    call_ret_OP_AL_32I_fu_234_ap_ready;
wire   [6:0] call_ret_OP_AL_32I_fu_234_func7_val;
wire   [2:0] call_ret_OP_AL_32I_fu_234_func3_val;
wire   [31:0] call_ret_OP_AL_32I_fu_234_ap_return_0;
wire   [0:0] call_ret_OP_AL_32I_fu_234_ap_return_1;
reg   [31:0] ap_phi_mux_agg_result_result_0_phi_fu_129_p24;
wire   [6:0] opcode_fu_260_p1;
wire   [31:0] grp_fu_246_p2;
wire   [31:0] shl_ln30_fu_441_p2;
wire   [31:0] shl_ln1_fu_448_p3;
wire   [2:0] func3_fu_264_p4;
reg   [31:0] ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24;
wire   [31:0] tmp_7_fu_424_p4;
wire  signed [31:0] sext_ln27_fu_392_p1;
wire  signed [31:0] sext_ln5_5_fu_485_p1;
wire  signed [31:0] sext_ln5_4_fu_512_p1;
wire  signed [31:0] sext_ln5_3_fu_537_p1;
wire  signed [31:0] sext_ln5_2_fu_556_p1;
wire  signed [31:0] sext_ln5_1_fu_575_p1;
wire  signed [31:0] sext_ln5_fu_594_p1;
reg   [0:0] ap_phi_mux_agg_result_valid_0_phi_fu_198_p24;
wire   [0:0] icmp_ln32_fu_397_p2;
wire  signed [19:0] imm_31_12_fu_286_p4;
wire   [0:0] tmp_fu_300_p3;
wire   [0:0] tmp_1_fu_308_p3;
wire   [5:0] tmp_s_fu_316_p4;
wire   [3:0] tmp_2_fu_326_p4;
wire   [7:0] tmp_3_fu_350_p4;
wire   [0:0] tmp_4_fu_360_p3;
wire   [9:0] tmp_5_fu_368_p4;
wire   [20:0] shl_ln_fu_378_p6;
wire   [11:0] tmp_6_fu_404_p4;
wire   [31:0] zext_ln34_fu_414_p1;
wire   [31:0] add_ln34_fu_418_p2;
wire  signed [31:0] sext_ln21_fu_296_p1;
wire   [31:0] add_ln30_fu_435_p2;
wire   [0:0] grp_fu_254_p2;
wire   [0:0] xor_ln14_fu_457_p2;
wire   [13:0] shl_ln3_fu_463_p6;
wire   [13:0] mdf_5_fu_477_p3;
wire   [13:0] shl_ln2_fu_490_p6;
wire   [13:0] mdf_4_fu_504_p3;
wire   [0:0] icmp_ln12_fu_517_p2;
wire   [0:0] xor_ln12_fu_523_p2;
wire   [12:0] imm_fu_336_p6;
wire   [12:0] mdf_3_fu_529_p3;
wire   [0:0] icmp_ln11_fu_542_p2;
wire   [12:0] mdf_2_fu_548_p3;
wire   [0:0] icmp_ln10_fu_561_p2;
wire   [12:0] mdf_1_fu_567_p3;
wire   [0:0] icmp_ln9_fu_580_p2;
wire   [12:0] mdf_fu_586_p3;
wire    ap_ce_reg;

top_module_OP_AL_32I call_ret_OP_AL_32I_fu_234(
    .ap_ready(call_ret_OP_AL_32I_fu_234_ap_ready),
    .inst_val(inst_val),
    .func7_val(call_ret_OP_AL_32I_fu_234_func7_val),
    .func3_val(call_ret_OP_AL_32I_fu_234_func3_val),
    .op1_val(op1_val),
    .op2_val(op2_val),
    .ap_return_0(call_ret_OP_AL_32I_fu_234_ap_return_0),
    .ap_return_1(call_ret_OP_AL_32I_fu_234_ap_return_1)
);

always @ (*) begin
    if (((func3_fu_264_p4 == 3'd0) & (opcode_fu_260_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = sext_ln5_fu_594_p1;
    end else if (((func3_fu_264_p4 == 3'd1) & (opcode_fu_260_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = sext_ln5_1_fu_575_p1;
    end else if (((func3_fu_264_p4 == 3'd4) & (opcode_fu_260_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = sext_ln5_2_fu_556_p1;
    end else if (((func3_fu_264_p4 == 3'd5) & (opcode_fu_260_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = sext_ln5_3_fu_537_p1;
    end else if (((func3_fu_264_p4 == 3'd6) & (opcode_fu_260_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = sext_ln5_4_fu_512_p1;
    end else if (((func3_fu_264_p4 == 3'd7) & (opcode_fu_260_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = sext_ln5_5_fu_485_p1;
    end else if ((((func3_fu_264_p4 == 3'd2) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd3) & (opcode_fu_260_p1 == 7'd99)))) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = 32'd0;
    end else if ((opcode_fu_260_p1 == 7'd111)) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = sext_ln27_fu_392_p1;
    end else if ((opcode_fu_260_p1 == 7'd103)) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = tmp_7_fu_424_p4;
    end else if (((opcode_fu_260_p1 == 7'd23) | (opcode_fu_260_p1 == 7'd55) | (~(opcode_fu_260_p1 == 7'd103) & ~(opcode_fu_260_p1 == 7'd111) & ~(opcode_fu_260_p1 == 7'd23) & ~(opcode_fu_260_p1 == 7'd55) & ~(opcode_fu_260_p1 == 7'd99)))) begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = 32'd4;
    end else begin
        ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24 = 'bx;
    end
end

always @ (*) begin
    if ((((func3_fu_264_p4 == 3'd0) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd1) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd4) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd5) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd6) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd7) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd2) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd3) & (opcode_fu_260_p1 == 7'd99)))) begin
        ap_phi_mux_agg_result_result_0_phi_fu_129_p24 = 32'd0;
    end else if ((opcode_fu_260_p1 == 7'd55)) begin
        ap_phi_mux_agg_result_result_0_phi_fu_129_p24 = shl_ln1_fu_448_p3;
    end else if ((opcode_fu_260_p1 == 7'd23)) begin
        ap_phi_mux_agg_result_result_0_phi_fu_129_p24 = shl_ln30_fu_441_p2;
    end else if (((opcode_fu_260_p1 == 7'd103) | (opcode_fu_260_p1 == 7'd111))) begin
        ap_phi_mux_agg_result_result_0_phi_fu_129_p24 = grp_fu_246_p2;
    end else if ((~(opcode_fu_260_p1 == 7'd103) & ~(opcode_fu_260_p1 == 7'd111) & ~(opcode_fu_260_p1 == 7'd23) & ~(opcode_fu_260_p1 == 7'd55) & ~(opcode_fu_260_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_result_0_phi_fu_129_p24 = call_ret_OP_AL_32I_fu_234_ap_return_0;
    end else begin
        ap_phi_mux_agg_result_result_0_phi_fu_129_p24 = 'bx;
    end
end

always @ (*) begin
    if ((((func3_fu_264_p4 == 3'd2) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd3) & (opcode_fu_260_p1 == 7'd99)))) begin
        ap_phi_mux_agg_result_valid_0_phi_fu_198_p24 = 1'd0;
    end else if (((opcode_fu_260_p1 == 7'd111) | (opcode_fu_260_p1 == 7'd23) | (opcode_fu_260_p1 == 7'd55) | ((func3_fu_264_p4 == 3'd0) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd1) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd4) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd5) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd6) & (opcode_fu_260_p1 == 7'd99)) | ((func3_fu_264_p4 == 3'd7) & (opcode_fu_260_p1 == 7'd99)))) begin
        ap_phi_mux_agg_result_valid_0_phi_fu_198_p24 = 1'd1;
    end else if ((opcode_fu_260_p1 == 7'd103)) begin
        ap_phi_mux_agg_result_valid_0_phi_fu_198_p24 = icmp_ln32_fu_397_p2;
    end else if ((~(opcode_fu_260_p1 == 7'd103) & ~(opcode_fu_260_p1 == 7'd111) & ~(opcode_fu_260_p1 == 7'd23) & ~(opcode_fu_260_p1 == 7'd55) & ~(opcode_fu_260_p1 == 7'd99))) begin
        ap_phi_mux_agg_result_valid_0_phi_fu_198_p24 = call_ret_OP_AL_32I_fu_234_ap_return_1;
    end else begin
        ap_phi_mux_agg_result_valid_0_phi_fu_198_p24 = 'bx;
    end
end

assign add_ln30_fu_435_p2 = (pc_val + 32'd12);

assign add_ln34_fu_418_p2 = (zext_ln34_fu_414_p1 + op1_val);

assign ap_ready = 1'b1;

assign call_ret_OP_AL_32I_fu_234_func3_val = {{inst_val[14:12]}};

assign call_ret_OP_AL_32I_fu_234_func7_val = {{inst_val[31:25]}};

assign func3_fu_264_p4 = {{inst_val[14:12]}};

assign grp_fu_246_p2 = (pc_val + 32'd4);

assign grp_fu_254_p2 = ((op1_val < op2_val) ? 1'b1 : 1'b0);

assign icmp_ln10_fu_561_p2 = ((op1_val != op2_val) ? 1'b1 : 1'b0);

assign icmp_ln11_fu_542_p2 = (($signed(op1_val) < $signed(op2_val)) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_517_p2 = (($signed(op2_val) < $signed(op1_val)) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_397_p2 = ((func3_fu_264_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_580_p2 = ((op1_val == op2_val) ? 1'b1 : 1'b0);

assign imm_31_12_fu_286_p4 = {{inst_val[31:12]}};

assign imm_fu_336_p6 = {{{{{tmp_fu_300_p3}, {tmp_1_fu_308_p3}}, {tmp_s_fu_316_p4}}, {tmp_2_fu_326_p4}}, {1'd0}};

assign mdf_1_fu_567_p3 = ((icmp_ln10_fu_561_p2[0:0] == 1'b1) ? imm_fu_336_p6 : 13'd4);

assign mdf_2_fu_548_p3 = ((icmp_ln11_fu_542_p2[0:0] == 1'b1) ? imm_fu_336_p6 : 13'd4);

assign mdf_3_fu_529_p3 = ((xor_ln12_fu_523_p2[0:0] == 1'b1) ? imm_fu_336_p6 : 13'd4);

assign mdf_4_fu_504_p3 = ((grp_fu_254_p2[0:0] == 1'b1) ? shl_ln2_fu_490_p6 : 14'd4);

assign mdf_5_fu_477_p3 = ((xor_ln14_fu_457_p2[0:0] == 1'b1) ? shl_ln3_fu_463_p6 : 14'd4);

assign mdf_fu_586_p3 = ((icmp_ln9_fu_580_p2[0:0] == 1'b1) ? imm_fu_336_p6 : 13'd4);

assign opcode_fu_260_p1 = inst_val[6:0];

assign sext_ln21_fu_296_p1 = imm_31_12_fu_286_p4;

assign sext_ln27_fu_392_p1 = $signed(shl_ln_fu_378_p6);

assign sext_ln5_1_fu_575_p1 = $signed(mdf_1_fu_567_p3);

assign sext_ln5_2_fu_556_p1 = $signed(mdf_2_fu_548_p3);

assign sext_ln5_3_fu_537_p1 = $signed(mdf_3_fu_529_p3);

assign sext_ln5_4_fu_512_p1 = $signed(mdf_4_fu_504_p3);

assign sext_ln5_5_fu_485_p1 = $signed(mdf_5_fu_477_p3);

assign sext_ln5_fu_594_p1 = $signed(mdf_fu_586_p3);

assign shl_ln1_fu_448_p3 = {{imm_31_12_fu_286_p4}, {12'd0}};

assign shl_ln2_fu_490_p6 = {{{{{tmp_fu_300_p3}, {tmp_1_fu_308_p3}}, {tmp_s_fu_316_p4}}, {tmp_2_fu_326_p4}}, {2'd0}};

assign shl_ln30_fu_441_p2 = sext_ln21_fu_296_p1 << add_ln30_fu_435_p2;

assign shl_ln3_fu_463_p6 = {{{{{tmp_fu_300_p3}, {tmp_1_fu_308_p3}}, {tmp_s_fu_316_p4}}, {tmp_2_fu_326_p4}}, {2'd0}};

assign shl_ln_fu_378_p6 = {{{{{tmp_fu_300_p3}, {tmp_3_fu_350_p4}}, {tmp_4_fu_360_p3}}, {tmp_5_fu_368_p4}}, {1'd0}};

assign tmp_1_fu_308_p3 = inst_val[32'd7];

assign tmp_2_fu_326_p4 = {{inst_val[11:8]}};

assign tmp_3_fu_350_p4 = {{inst_val[19:12]}};

assign tmp_4_fu_360_p3 = inst_val[32'd20];

assign tmp_5_fu_368_p4 = {{inst_val[30:21]}};

assign tmp_6_fu_404_p4 = {{inst_val[31:20]}};

assign tmp_7_fu_424_p4 = {add_ln34_fu_418_p2[32-1:1], |(1'd0)};

assign tmp_fu_300_p3 = inst_val[32'd31];

assign tmp_s_fu_316_p4 = {{inst_val[30:25]}};

assign xor_ln12_fu_523_p2 = (icmp_ln12_fu_517_p2 ^ 1'd1);

assign xor_ln14_fu_457_p2 = (grp_fu_254_p2 ^ 1'd1);

assign zext_ln34_fu_414_p1 = tmp_6_fu_404_p4;

assign ap_return_0 = ap_phi_mux_agg_result_result_0_phi_fu_129_p24;

assign ap_return_1 = ap_phi_mux_agg_result_next_pc_0_phi_fu_165_p24;

assign ap_return_2 = ap_phi_mux_agg_result_valid_0_phi_fu_198_p24;

endmodule //top_module_hart
