// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hart_OP_AL_32I (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        opcode_val,
        func7_val,
        func3_val,
        op1_val,
        op2_val,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] opcode_val;
input  [6:0] func7_val;
input  [2:0] func3_val;
input  [31:0] op1_val;
input  [31:0] op2_val;
output  [31:0] ap_return_0;
output  [0:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return_0;
reg[0:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_261_p2;
wire   [6:0] opcode_val_read_read_fu_78_p2;
wire   [2:0] func3_val_read_read_fu_66_p2;
wire   [6:0] func7_val_read_read_fu_72_p2;
wire   [31:0] grp_fu_267_p2;
wire   [31:0] grp_fu_273_p2;
wire   [31:0] grp_fu_279_p2;
wire   [31:0] grp_fu_293_p2;
wire   [0:0] tmp_fu_353_p3;
wire   [0:0] grp_fu_285_p3;
wire   [31:0] grp_fu_305_p2;
wire   [31:0] rd_val_13_fu_371_p2;
wire   [31:0] zext_ln53_fu_383_p1;
wire   [31:0] zext_ln52_fu_393_p1;
wire   [31:0] shr_i4_fu_401_p2;
wire   [31:0] ashr_ln65_fu_407_p2;
reg   [0:0] tmp_1_reg_534;
wire   [31:0] ashr_ln37_fu_419_p2;
wire   [31:0] shl_ln37_fu_425_p2;
wire   [31:0] rd_val_12_fu_431_p2;
wire   [31:0] zext_ln24_fu_443_p1;
wire   [31:0] zext_ln23_fu_453_p1;
wire   [31:0] shl_ln22_fu_457_p2;
wire   [31:0] ashr_ln22_fu_463_p2;
reg   [31:0] tmp56_0_reg_84;
reg   [31:0] ap_phi_mux_rd_val_14_phi_fu_97_p60;
reg   [31:0] rd_val_14_reg_93;
wire   [0:0] icmp_ln58_fu_361_p2;
wire   [31:0] xor_ln37_1_fu_469_p2;
wire    ap_CS_fsm_state2;
reg   [0:0] ap_phi_mux_status_phi_fu_169_p60;
reg   [0:0] status_reg_164;
wire   [31:0] grp_fu_299_p2;
wire   [5:0] shamt_fu_349_p1;
wire   [31:0] zext_ln58_fu_367_p1;
wire   [0:0] rd_val_2_fu_377_p2;
wire   [0:0] rd_val_1_fu_387_p2;
wire   [31:0] zext_ln65_fu_397_p1;
wire   [31:0] xor_ln37_fu_413_p2;
wire   [0:0] rd_val_9_fu_437_p2;
wire   [0:0] rd_val_8_fu_447_p2;
reg   [31:0] ap_return_0_preg;
reg   [0:0] ap_return_1_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_condition_409;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_return_0_preg <= ap_phi_mux_rd_val_14_phi_fu_97_p60;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_return_1_preg <= ap_phi_mux_status_phi_fu_169_p60;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_534 == 1'd1))) begin
        rd_val_14_reg_93 <= xor_ln37_1_fu_469_p2;
    end else if (((tmp_fu_353_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd1) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= shl_ln22_fu_457_p2;
    end else if (((tmp_fu_353_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd1) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= ashr_ln22_fu_463_p2;
    end else if (((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd2) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= zext_ln23_fu_453_p1;
    end else if (((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd3) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= zext_ln24_fu_443_p1;
    end else if (((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd0) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= rd_val_12_fu_431_p2;
    end else if (((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd1) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln58_fu_361_p2 == 1'd1))) begin
        rd_val_14_reg_93 <= rd_val_13_fu_371_p2;
    end else if ((((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd0) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd0) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)))) begin
        rd_val_14_reg_93 <= grp_fu_279_p2;
    end else if (((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd2) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= zext_ln52_fu_393_p1;
    end else if (((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd3) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= zext_ln53_fu_383_p1;
    end else if ((((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd4) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd4) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)))) begin
        rd_val_14_reg_93 <= grp_fu_273_p2;
    end else if ((((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd6) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd6) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)))) begin
        rd_val_14_reg_93 <= grp_fu_267_p2;
    end else if ((((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd7) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd7) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)))) begin
        rd_val_14_reg_93 <= grp_fu_261_p2;
    end else if ((((grp_fu_285_p3 == 1'd0) & (tmp_fu_353_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)))) begin
        rd_val_14_reg_93 <= grp_fu_293_p2;
    end else if ((((grp_fu_285_p3 == 1'd0) & (tmp_fu_353_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)))) begin
        rd_val_14_reg_93 <= grp_fu_305_p2;
    end else if (((grp_fu_285_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= shr_i4_fu_401_p2;
    end else if (((grp_fu_285_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_val_14_reg_93 <= ashr_ln65_fu_407_p2;
    end else if (((~(func3_val_read_read_fu_66_p2 == 3'd5) & ~(func3_val_read_read_fu_66_p2 == 3'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | (~(func7_val_read_read_fu_72_p2 == 7'd32) & ~(func7_val_read_read_fu_72_p2 == 7'd0) & (ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | (~(func7_val_read_read_fu_72_p2 == 7'd32) & ~(func7_val_read_read_fu_72_p2 == 7'd0) & (ap_start == 1'b1) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | (~(opcode_val_read_read_fu_78_p2 == 7'd51) & ~(opcode_val_read_read_fu_78_p2 == 7'd19) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd1) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln58_fu_361_p2 == 1'd0)))) begin
        rd_val_14_reg_93 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_fu_285_p3 == 1'd0) & (tmp_fu_353_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((grp_fu_285_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((grp_fu_285_p3 == 1'd0) & (tmp_fu_353_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_534 == 1'd1)) | ((tmp_fu_353_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 
    == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd1) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((grp_fu_285_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd0) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd0) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd4) & (opcode_val_read_read_fu_78_p2 
    == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd6) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd0) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd4) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd6) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd7) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd2) & (opcode_val_read_read_fu_78_p2 == 7'd51) 
    & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd3) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd7) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd1) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln58_fu_361_p2 == 1'd1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd2) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd3) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd1) & (ap_start 
    == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_353_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd0) & (func3_val_read_read_fu_66_p2 == 3'd1) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)))) begin
        status_reg_164 <= 1'd0;
    end else if (((~(func3_val_read_read_fu_66_p2 == 3'd5) & ~(func3_val_read_read_fu_66_p2 == 3'd0) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | (~(func7_val_read_read_fu_72_p2 == 7'd32) & ~(func7_val_read_read_fu_72_p2 == 7'd0) & (ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1)) | (~(func7_val_read_read_fu_72_p2 == 7'd32) & ~(func7_val_read_read_fu_72_p2 == 7'd0) & (ap_start == 1'b1) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1)) | (~(opcode_val_read_read_fu_78_p2 == 7'd51) & ~(opcode_val_read_read_fu_78_p2 == 7'd19) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (func3_val_read_read_fu_66_p2 == 3'd1) & (opcode_val_read_read_fu_78_p2 == 7'd19) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln58_fu_361_p2 == 1'd0)))) begin
        status_reg_164 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_409)) begin
        if ((tmp_fu_353_p3 == 1'd0)) begin
            tmp56_0_reg_84 <= ashr_ln37_fu_419_p2;
        end else if ((tmp_fu_353_p3 == 1'd1)) begin
            tmp56_0_reg_84 <= shl_ln37_fu_425_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_1_reg_534 <= op1_val[32'd31];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_534 == 1'd1))) begin
        ap_phi_mux_rd_val_14_phi_fu_97_p60 = xor_ln37_1_fu_469_p2;
    end else begin
        ap_phi_mux_rd_val_14_phi_fu_97_p60 = rd_val_14_reg_93;
    end
end

always @ (*) begin
    if (((func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_534 == 1'd1))) begin
        ap_phi_mux_status_phi_fu_169_p60 = 1'd0;
    end else begin
        ap_phi_mux_status_phi_fu_169_p60 = status_reg_164;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_return_0 = ap_phi_mux_rd_val_14_phi_fu_97_p60;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_return_1 = ap_phi_mux_status_phi_fu_169_p60;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_condition_409 = ((grp_fu_285_p3 == 1'd1) & (ap_start == 1'b1) & (func7_val_read_read_fu_72_p2 == 7'd32) & (func3_val_read_read_fu_66_p2 == 3'd5) & (opcode_val_read_read_fu_78_p2 == 7'd51) & (1'b1 == ap_CS_fsm_state1));
end

assign ashr_ln22_fu_463_p2 = $signed(op1_val) >>> grp_fu_299_p2;

assign ashr_ln37_fu_419_p2 = $signed(xor_ln37_fu_413_p2) >>> op2_val;

assign ashr_ln65_fu_407_p2 = $signed(op1_val) >>> zext_ln65_fu_397_p1;

assign func3_val_read_read_fu_66_p2 = func3_val;

assign func7_val_read_read_fu_72_p2 = func7_val;

assign grp_fu_261_p2 = (op2_val & op1_val);

assign grp_fu_267_p2 = (op2_val | op1_val);

assign grp_fu_273_p2 = (op2_val ^ op1_val);

assign grp_fu_279_p2 = (op2_val + op1_val);

assign grp_fu_285_p3 = op1_val[32'd31];

assign grp_fu_293_p2 = op1_val >> op2_val;

assign grp_fu_299_p2 = (32'd0 - op2_val);

assign grp_fu_305_p2 = op1_val << grp_fu_299_p2;

assign icmp_ln58_fu_361_p2 = ((func7_val == 7'd0) ? 1'b1 : 1'b0);

assign opcode_val_read_read_fu_78_p2 = opcode_val;

assign rd_val_12_fu_431_p2 = (op1_val - op2_val);

assign rd_val_13_fu_371_p2 = op1_val << zext_ln58_fu_367_p1;

assign rd_val_1_fu_387_p2 = (($signed(op2_val) > $signed(op1_val)) ? 1'b1 : 1'b0);

assign rd_val_2_fu_377_p2 = ((op2_val > op1_val) ? 1'b1 : 1'b0);

assign rd_val_8_fu_447_p2 = (($signed(op1_val) < $signed(op2_val)) ? 1'b1 : 1'b0);

assign rd_val_9_fu_437_p2 = ((op1_val < op2_val) ? 1'b1 : 1'b0);

assign shamt_fu_349_p1 = op2_val[5:0];

assign shl_ln22_fu_457_p2 = op1_val << op2_val;

assign shl_ln37_fu_425_p2 = xor_ln37_fu_413_p2 << grp_fu_299_p2;

assign shr_i4_fu_401_p2 = op1_val >> zext_ln65_fu_397_p1;

assign tmp_fu_353_p3 = op2_val[32'd31];

assign xor_ln37_1_fu_469_p2 = (tmp56_0_reg_84 ^ 32'd4294967295);

assign xor_ln37_fu_413_p2 = (op1_val ^ 32'd4294967295);

assign zext_ln23_fu_453_p1 = rd_val_8_fu_447_p2;

assign zext_ln24_fu_443_p1 = rd_val_9_fu_437_p2;

assign zext_ln52_fu_393_p1 = rd_val_1_fu_387_p2;

assign zext_ln53_fu_383_p1 = rd_val_2_fu_377_p2;

assign zext_ln58_fu_367_p1 = shamt_fu_349_p1;

assign zext_ln65_fu_397_p1 = shamt_fu_349_p1;

endmodule //hart_OP_AL_32I
