set SynModuleInfo {
  {SRCNAME OP_AL_32I MODELNAME OP_AL_32I RTLNAME hart_OP_AL_32I}
  {SRCNAME hart MODELNAME hart RTLNAME hart IS_TOP 1
    SUBMODULES {
      {MODELNAME hart_rf_RAM_AUTO_1R1W RTLNAME hart_rf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
